# ----
# Site

title: Commerce Docs
description: API guides for Nike developers
permalink: none
url: https://supreme-barnacle-5231cb32.pages.github.io
baseurl: /nike-cx/nde-devportal-docs

# -----
# Build

timezone: Etc/UTC

# exclude these files (relative to source directory) from the conversion
exclude:
  - templates/

defaults:
  -
    scope:
      path: ""
    values:
      layout: two-column

kramdown:
  # parse markdown inside block-level HTML tag
  #parse_block_html: true

# publish from a source dir to a destination dir
destination: ./_site/

# only convert changed files
incremental: true