# ----
# Site

title: Aviator
description: Jekyll template for API documentation.
url: https://example.com
google_analytics_key:
permalink: none

# -----
# Build

timezone: Etc/UTC

# exclude these files (relative to source directory) from the conversion
exclude:
  - templates/

plugins:
# minifies html, css, js
#   - jekyll-minifier

# jekyll-minifier doesn't seem to work without this setting related to ES6 syntax
#jekyll-minifier:
#  uglifier_args:
#    harmony: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: two-column
      toctitle: "NDe Docs Home"

kramdown:
  # parse markdown inside block-level HTML tag
  #parse_block_html: true

# publish to/from
source: src
destination: ./content/

# only convert changed files
#incremental: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css