@startuml
title Example of API Calls to <font color =orange>Nike Checkout</font> (Web App)

participant Client
participant Carts
participant "Cart Reviews"
participant "Shipping Options"
participant "Checkout Preview"
participant "Payment Options"
participant "Stored Payments"
participant "Payment Preview"
participant "Checkout Submit"

group Cart
note over Carts, "Cart Reviews" #3F7FBF: Cart optional for checkout
Client->Carts: PUT ///buy/carts/v2/{id}//: Cart items and quantities
Carts-[#blue]->Client: Validated cart with item prices and subtotals

Client->"Cart Reviews": POST ///buy/cart_reviews/v1///: Cart items, shipping country
"Cart Reviews"-[#blue]->Client: Cart summary with estimated taxes, delivery date(s), ship group(s)
end

group Shipping & Checkout Preview

Client->"Shipping Options": POST ///buy/shipping_options/v2//: Items, shipping address
note over "Shipping Options" #3F7FBF: Shipping Options optional if shipping methods are always known
"Shipping Options"-[#blue]->Client: Available shipping methods w/costs and estimated delivery dates

Client->"Checkout Preview": PUT ///buy/checkout_previews/v2/{id}//: Items, shipping address, shipping method
"Checkout Preview"-[#blue]->Client: 202 with job ID and ETA
loop
Client->"Checkout Preview": GET ///buy/checkout_previews/v2/jobs/{id}//
note over "Checkout Preview" #lightgreen: Wait ETA, Poll /jobs until job is done
"Checkout Preview"-[#blue]->Client: Item prices/taxes, shipping prices/taxes, estimated delivery date, order subtotals
end loop
end

group Payment
note over "Payment Options" #3F7FBF: Payment Options optional if payment methods are always known
Client->"Payment Options": POST ///payment/options/v2//: Items, currency and country
"Payment Options"-[#blue]->Client: Available payment options
note over "Stored Payments" #3F7FBF: Stored Payments optional if saved payment methods or gift cards not supported by UX
Client->"Stored Payments": POST ///commerce/storedpayments/consumer/storedpayments?currency=USD//: Upmid, shipping address
"Stored Payments"-[#blue]->Client: Available stored payments w/paymentId, balance (gift card only)

Client->"Payment Preview": POST ///payment/preview/v2//: Items, shipping address, billing address, payment tokens
"Payment Preview"-[#blue]->Client: 202 with job ID and ETA
loop
Client->"Payment Preview": GET ///payment/previews/v2/jobs/{id}//
note over "Payment Preview" #lightgreen: Wait ETA, Poll /jobs until job is done
"Payment Preview"-[#blue]->Client: Validated payments allocated to total order amount
end loop
end

group Checkout Submit
Client->"Checkout Submit": PUT ///buy/checkouts/v2/{id}//: Items, shipping address, shipping method, payment token
"Checkout Submit"-[#blue]->Client: 202 with job ID and ETA
loop
Client->"Checkout Submit": GET ///buy/checkoutz/v2/jobs/{id}//
note over "Checkout Submit" #lightgreen: Wait ETA, Poll /jobs until job is done
"Checkout Submit"-[#blue]->Client: Item prices/taxes, shipping prices/taxes/groups, estimated delivery date(s), order subtotals
end loop
end

@enduml